Add Must-gather after every task on airflow
cloud-bulldozer/airflow-kubernetes pull request #51
Opened 2021-09-06 17:34 UTC by Harshith-umesh

### Description
This PR adds an option to enable must-gather after any/every task on airflow.We have to set the env var MUST_GATHER_EACH_TASK in the env section of a task on the defaults.json or benchmarks.json file to enable or disable the must-gather step after that task.
The collected must-gather tar files will be sent to snappy.

2021-09-07 17:24 UTC, whitleykeith commented
Maybe I'm not remembering the last meeting we had about this, but I thought the decision was to hold off on this for now and investigate using a centralized log store like Loki to solve this issue?

2021-09-07 17:27 UTC, Harshith-umesh commented
> Maybe I'm not remembering the last meeting we had about this, but I thought the decision was to hold off on this for now and investigate using a centralized log store like Loki to solve this issue?

i don't think that was the consensus that we reached , we should ask joe about this

2021-09-08 14:37 UTC, dry923 commented on dags/openshift_nightlies/tasks/benchmarks/defaults.json
> +
extra line

2021-09-08 14:37 UTC, dry923 commented on dags/openshift_nightlies/tasks/benchmarks/defaults.json
> +
extra line

2021-10-05 18:55 UTC, jtaleric commented
Do we want to keep this? If we do, lets just have this `exit 0` at the end. We shouldn't fail the run if must-gather fails.

2021-10-06 20:07 UTC, mohit-sheth approved these changes
LGTM

2021-10-11 15:04 UTC, whitleykeith requested changes

2021-10-11 15:04 UTC, whitleykeith commented on dags/openshift_nightlies/scripts/run_benchmark.sh
> +        ./ocp_diagnosis.sh
@Harshith-umesh

2021-10-13 13:52 UTC, whitleykeith approved these changes

2021-10-13 13:58 UTC, merged