add ocp_network_type var from vault
cloud-bulldozer/airflow-kubernetes pull request #53
Opened 2021-09-07 14:00 UTC by amitsagtani97

### Description
Get network type var from vault to override in case we need to run test on a particular network type in shift-on-stack CI

2021-09-07 17:23 UTC, whitleykeith commented
why do you need to add this logic via secret instead of just making a profile for each network type, similar to how we do it for the cloud deployments?

2021-09-14 17:04 UTC, masco commented
@whitleykeith currently shift on stack is running on a scale lab LTA allocation and we have just one deployment of OSP. we can't run the jobs parallelly on it. but still, we need to test all the three SDNs(Kuryr, OpenshiftSDN, and OVNKubernetes). so we thought choosing the SDN using the days logic is easier comparatively having three jobs and synchronizing between them. The SDN is chosen automatically based on the date for any job triggered by a cron job. this vault variable is used only if we want to test any particular SDN manually.

2021-10-05 18:52 UTC, jtaleric requested changes
I don't think this makes sense to do a CNI based on the day it ran... the nightly builds could be different, so why would you compare them? 

I would prefer we focus on a single CNI.

2021-10-06 09:33 UTC, amitsagtani97 commented
@jtaleric makes sense! Removed the day based logic and set specific CNI for a particular DAG.
Closing this PR.

2021-10-06 09:33 UTC, closed without merging